sudo: false
language: java
jdk:
  - oraclejdk8
after_success:
- mvn clean cobertura:cobertura coveralls:report
- mvn clean deploy --settings settings.xml
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/8a01013ab5c4177cc0be
    on_success: change
    on_failure: always
    on_start: false