sudo: false
language: java
jdk:
  - oraclejdk7
addons:
  apt:
    packages:
    - oracle-java7-installer
script:
 - sonar-scanner -Dsonar.login=$SONAR_TOKEN
 - "./build.sh"
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/ef8645d0a8959f3f49c2
    on_success: change
    on_failure: always
    on_start: false
env:
  global:
    secure: Q0AmjxrPpFTdsAwqbiwweQexDiIc5Nqq8MqnFvSHMZ2uDuubLmyWJ8fmLNrQu1Ph23g9cnmkHX8OFU9lE55IGQzmOMcN5k/iFlXXwtCvT7Iiv6GNquDtgPWWDAdkNmY5WPF5QUH4xw5sumD0G9UoaByq/d/TMYAr/j7LrhO6RJfV4nk/5XF8PXIRCQwMhlJvZE0KdQeEm8Q/KuB8J4pilQ6ZoNH1yzc28JTs7isxedCweKr4ZHorm2bpT4xK8B6he0BwZXQqghJys+zTOY778D1/rKnffKMSA88OkYlmDyKXPju30r84iVoMYRjfWxaHE3cef6Hqhxw6b+plUqKH4EHt8nLwiqmFRLAlw/4Qf610fnQujGwL1Www68AI8W6pwsLkOtYL5IBivxtqx6g1k8t9qy+hd17dqy/E8bnk3xZ6SqhC9gghZZtXnnZUkQLcYE0uYinLKN19VD84mYFQTeERWjqKhN4HAsawE9k8zH1AqHqcDJvhbHaklpQryu/43/y6fHCyBsA541GghRujIf200HjTYvEjkHLSVvnaiu05/Pj8e7WpBFS0H+Z3bRj724C0FpGHFx8exzbdAwhy/bgDnuMn1hQMO44HoldKCkvHopGa3r9nLTPn9T3BpE5JysE9amxBmh47WlRplvIwP1e0wgcFObmIhFNoJbeljUA=
addons:
  sonarqube: true
