sudo: false
language: java
jdk:
  - oraclejdk8
after_success:
  - mvn jacoco:report coveralls:report
  - mvn deploy -DskipTests=true --settings settings.xml
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/14d2cdb95b5ee533def6
    on_success: change
    on_failure: always
    on_start: false